---
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate.SQL: WARN

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    enable:
      all: true
  tracing:
    sampling:
      probability: 1.0

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

  instance:
    prefer-ip-address: true

#services:
#  api-gateway:
#    port: 8080
#  config-server:
#    port: 8888
#  discovery-server:
#    port: 8761
#  auth-service:
#    port: 8081
#  order-service:
#    port: 8082
#  product-service:
#    port: 8083
#  inventory-service:
#    port: 8084
#  payment-service:
#    port: 8085
#  notification-service:
#    port: 8086
